export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const CURRENT_USER = "CURRENT_USER";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_ERROR = "CURRENT_USER_ERROR";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const GET_PHARMACY = "GET_PHARMACY";
export const GET_PHARMACY_SUCCESS = "GET_PHARMACY_SUCCESS";
export const GET_PHARMACY_ERROR = "GET_PHARMACY_ERROR";

export const LIST_PHARMACY = "LIST_PHARMACY";
export const LIST_PHARMACY_SUCCESS = "LIST_PHARMACY_SUCCESS";
export const LIST_PHARMACY_ERROR = "LIST_PHARMACY_ERROR";

export const CREATE_PHARMACY = "CREATE_PHARMACY";
export const CREATE_PHARMACY_SUCCESS = "CREATE_PHARMACY_SUCCESS";
export const CREATE_PHARMACY_ERROR = "CREATE_PHARMACY_ERROR";

export const UPDATE_PHARMACY = "UPDATE_PHARMACY";
export const UPDATE_PHARMACY_SUCCESS = "UPDATE_PHARMACY_SUCCESS";
export const UPDATE_PHARMACY_ERROR = "UPDATE_PHARMACY_ERROR";

export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_ERROR = "GET_CITIES_ERROR";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";

export const GET_STATES = "GET_STATES";
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const GET_STATES_ERROR = "GET_STATES_ERROR";

export const GET_MEDICINE_STORES = "GET_MEDICINE_STORES";
export const GET_MEDICINE_STORES_SUCCESS = "GET_MEDICINE_STORES_SUCCESS";
export const GET_MEDICINE_STORES_ERROR = "GET_MEDICINE_STORES_ERROR";

export const GET_PHARMACY_MSI = "GET_PHARMACY_MSI";
export const GET_PHARMACY_MSI_SUCCESS = "GET_PHARMACY_MSI_SUCCESS";
export const GET_PHARMACY_MSI_ERROR = "GET_PHARMACY_MSI_ERROR";

export const CREATE_PHARMACY_MSI = "CREATE_PHARMACY_MSI";
export const CREATE_PHARMACY_MSI_SUCCESS = "CREATE_PHARMACY_MSI_SUCCESS";
export const CREATE_PHARMACY_MSI_ERROR = "CREATE_PHARMACY_MSI_ERROR";

export const UPDATE_PHARMACY_MSI = "UPDATE_PHARMACY_MSI";
export const UPDATE_PHARMACY_MSI_SUCCESS = "UPDATE_PHARMACY_MSI_SUCCESS";
export const UPDATE_PHARMACY_MSI_ERROR = "UPDATE_PHARMACY_MSI_ERROR";

export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";

export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
